### 获取商品接口使用的登录凭证
# @name productLogin
POST {{baseUrl}}/api/v1/auth/login
Content-Type: application/json

{"login":"admin","password":"12345678"}

###

### 根据 ID 查询指定商品
GET {{baseUrl}}/api/v1/admin/products/1
Authorization: Bearer {{productLogin.response.body.$.data.access_token}}
Accept: application/json
